- name: Run account_info.yml playbook
  command: ansible-playbook -i localhost, -c local account_info.yml -v -e DIGITALOCEAN_TOKEN="pleasechangeit"
  args:
    chdir: /home/projects/awx/do-ansible-collection/playbooks
  register: account_info_output
