---
- name: Sync GitHub Repository and Run Ansible Playbooks
  hosts: all
  become: yes  # Use sudo privileges if needed
  tasks:
    - name: Change to the projects directory
      command: cd /home/projects/awx
      args:
        chdir: /home/projects/awx

    - name: Sync GitHub repository to local path
      git:
        repo: 'https://github.com/jamesoujj/do-ansible-collection.git'
        dest: '/home/projects/awx/do-ansible-collection'
        version: 'main'
        force: yes
      register: git_pull

    - name: Change to the playbooks directory
      command: cd /home/projects/awx/do-ansible-collection/playbooks
      args:
        chdir: /home/projects/awx/do-ansible-collection/playbooks

    - name: Run account_info.yml playbook
      command: ansible-playbook -i localhost, -c local account_info.yml -v
      register: account_info_output
      args:
        chdir: /home/projects/awx/do-ansible-collection/playbooks

    - name: Display account_info.yml output
      debug:
        msg: "{{ account_info_output.stdout }}"

    - name: Run balance_info.yml playbook
      command: ansible-playbook -i localhost, -c local balance_info.yml -v
      register: balance_info_output
      args:
        chdir: /home/projects/awx/do-ansible-collection/playbooks

    - name: Display balance_info.yml output
      debug:
        msg: "{{ balance_info_output.stdout }}"

    - name: Save outputs to a file
      copy:
        content: |
          Account Info Output:
          {{ account_info_output.stdout }}

          Balance Info Output:
          {{ balance_info_output.stdout }}
        dest: /tmp/ansible_playbook_results.txt
