---
- name: Sync GitHub Repository and Run Ansible Playbooks
  hosts: all
  become: yes  # Use sudo privileges if needed
  vars:
    DIGITALOCEAN_TOKEN: "{{ lookup('env', 'DIGITALOCEAN_TOKEN') }}"
  tasks:
    - name: Sync GitHub repository to local path
      git:
        repo: 'https://github.com/jamesoujj/do-ansible-collection.git'
        dest: '/home/projects/awx/do-ansible-collection'
        version: 'main'
        force: yes
      register: git_pull

    - name: Run account_info.yml playbook
      command: ansible-playbook -i localhost, -c local account_info.yml -v
      args:
        chdir: /home/projects/awx/do-ansible-collection/playbooks
      environment:
        DIGITALOCEAN_TOKEN: "{{ DIGITALOCEAN_TOKEN }}"
      register: account_info_output

    - name: Display account_info.yml output
      debug:
        msg: "{{ account_info_output.stdout }}"

    - name: Run balance_info.yml playbook
      command: ansible-playbook -i localhost, -c local balance_info.yml -v
      args:
        chdir: /home/projects/awx/do-ansible-collection/playbooks
      environment:
        DIGITALOCEAN_TOKEN: "{{ DIGITALOCEAN_TOKEN }}"
      register: balance_info_output

    - name: Display balance_info.yml output
      debug:
        msg: "{{ balance_info_output.stdout }}"

    - name: Run billing_history_info.yml playbook
      command: ansible-playbook -i localhost, -c local billing_history_info.yml -v
      args:
        chdir: /home/projects/awx/do-ansible-collection/playbooks
      environment:
        DIGITALOCEAN_TOKEN: "{{ DIGITALOCEAN_TOKEN }}"
      register: billing_history_output

    - name: Display billing_history_info.yml output
      debug:
        msg: "{{ billing_history_output.stdout }}"

    - name: Save outputs to a file
      copy:
        content: |
          Account Info Output:
          {{ account_info_output.stdout }}

          Balance Info Output:
          {{ balance_info_output.stdout }}

          Billing History Info Output:
          {{ billing_history_output.stdout }}
        dest: /tmp/ansible_playbook_results.txt
