---
- name: Gather System Information with Sudo
  hosts: all
  become: yes  # Use sudo privileges
  tasks:
    - name: Gather disk usage information
      command: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout }}"

    - name: Gather memory usage information
      command: free -m
      register: memory_usage

    - name: Display memory usage
      debug:
        msg: "{{ memory_usage.stdout }}"

    - name: Gather CPU information
      command: lscpu
      register: cpu_info

    - name: Display CPU information
      debug:
        msg: "{{ cpu_info.stdout }}"

    - name: Gather network interface information
      command: ip a
      register: network_info

    - name: Display network interface information
      debug:
        msg: "{{ network_info.stdout }}"
